# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 490)
        MainWindow.setMinimumSize(QtCore.QSize(780, 490))
        MainWindow.setMaximumSize(QtCore.QSize(780, 490))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("view/img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 780, 130))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("view/img/heardlogo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.view_fan = QtWidgets.QWidget(self.centralwidget)
        self.view_fan.setGeometry(QtCore.QRect(190, 130, 590, 320))
        self.view_fan.setObjectName("view_fan")

        self.out_text = QtWidgets.QTextBrowser(self.view_fan)
        self.out_text.setGeometry(QtCore.QRect(334, 50, 236, 179))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.out_text.setFont(font)
        self.out_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.out_text.setPlaceholderText("")
        self.out_text.setObjectName("out_text")

        self.butt_range = QtWidgets.QPushButton(self.view_fan)
        self.butt_range.setGeometry(QtCore.QRect(253, 130, 75, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(70)
        self.butt_range.setFont(font)
        self.butt_range.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.butt_range.setObjectName("butt_range")
        self.input_text = QtWidgets.QTextEdit(self.view_fan)
        self.input_text.setGeometry(QtCore.QRect(11, 50, 236, 179))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(65)
        font.setKerning(True)
        self.input_text.setFont(font)
        self.input_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.input_text.setObjectName("input_text")
        self.butt_return = QtWidgets.QPushButton(self.view_fan)
        self.butt_return.setGeometry(QtCore.QRect(10, 20, 75, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(70)
        self.butt_return.setFont(font)
        self.butt_return.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.butt_return.setObjectName("butt_return")

        self.label_bz = QtWidgets.QLabel(self.view_fan)
        self.label_bz.setGeometry(QtCore.QRect(330, -10, 101, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(50)
        self.label_bz.setFont(font)
        self.label_bz.setObjectName("label_bz")
        self.lien_bz = QtWidgets.QLineEdit(self.view_fan)
        self.lien_bz.setGeometry(QtCore.QRect(420, 0, 151, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lien_bz.setFont(font)
        self.lien_bz.setObjectName("lien_bz")

        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 130, 161, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.butt_fanyi = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butt_fanyi.sizePolicy().hasHeightForWidth())
        self.butt_fanyi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(50)
        self.butt_fanyi.setFont(font)
        self.butt_fanyi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.butt_fanyi.setObjectName("butt_fanyi")
        self.verticalLayout.addWidget(self.butt_fanyi)
        self.butt_wordTrain = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butt_wordTrain.sizePolicy().hasHeightForWidth())
        self.butt_wordTrain.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(50)
        self.butt_wordTrain.setFont(font)
        self.butt_wordTrain.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.butt_wordTrain.setObjectName("butt_wordTrain")
        self.verticalLayout.addWidget(self.butt_wordTrain)
        self.butt_words = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butt_words.sizePolicy().hasHeightForWidth())
        self.butt_words.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(50)
        self.butt_words.setFont(font)
        self.butt_words.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.butt_words.setObjectName("butt_words")
        self.verticalLayout.addWidget(self.butt_words)
        self.butt_erbook = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butt_erbook.sizePolicy().hasHeightForWidth())
        self.butt_erbook.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(50)
        self.butt_erbook.setFont(font)
        self.butt_erbook.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.butt_erbook.setObjectName("butt_erbook")
        self.verticalLayout.addWidget(self.butt_erbook)
        self.butt_test = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butt_test.sizePolicy().hasHeightForWidth())
        self.butt_test.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(50)
        self.butt_test.setFont(font)
        self.butt_test.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.butt_test.setObjectName("butt_test")
        self.verticalLayout.addWidget(self.butt_test)
        self.butt_guanWang = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butt_guanWang.sizePolicy().hasHeightForWidth())
        self.butt_guanWang.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(50)
        self.butt_guanWang.setFont(font)
        self.butt_guanWang.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.butt_guanWang.setObjectName("butt_guanWang")
        self.verticalLayout.addWidget(self.butt_guanWang)
        self.view_fan.raise_()
        self.label.raise_()
        self.layoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 780, 23))
        self.menuBar.setObjectName("menuBar")
        self.user = QtWidgets.QMenu(self.menuBar)
        self.user.setObjectName("user")
        self.help = QtWidgets.QMenu(self.menuBar)
        self.help.setObjectName("help")
        self.help_about = QtWidgets.QMenu(self.help)
        self.help_about.setObjectName("help_about")
        MainWindow.setMenuBar(self.menuBar)
        self.user_set = QtWidgets.QAction(MainWindow)
        self.user_set.setObjectName("user_set")
        self.user_add = QtWidgets.QAction(MainWindow)
        self.user_add.setObjectName("user_add")
        self.user_out = QtWidgets.QAction(MainWindow)
        self.user_out.setObjectName("user_out")
        self.help_fund = QtWidgets.QAction(MainWindow)
        self.help_fund.setObjectName("help_fund")
        self.help_about_help = QtWidgets.QAction(MainWindow)
        self.help_about_help.setObjectName("help_about_help")
        self.help_about_check = QtWidgets.QAction(MainWindow)
        self.help_about_check.setObjectName("help_about_check")
        self.user.addAction(self.user_set)
        self.user.addSeparator()
        self.user.addAction(self.user_add)
        self.user.addSeparator()
        self.user.addAction(self.user_out)
        self.help_about.addAction(self.help_about_help)
        self.help_about.addSeparator()
        self.help_about.addAction(self.help_about_check)
        self.help.addAction(self.help_fund)
        self.help.addSeparator()
        self.help.addAction(self.help_about.menuAction())
        self.menuBar.addAction(self.user.menuAction())
        self.menuBar.addAction(self.help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #设置按钮和主界面背景图片border-image background-image image
        style_manwindow = '''#MainWindow{image:url('view/img/main_bj.png');}'''
        MainWindow.setStyleSheet(style_manwindow)

        style_bt1 = '''#butt_fanyi{background-image:url('view/img/but-fanyi.png');}'''
        style_bt2 = '''#butt_wordTrain{background-image:url('view/img/but-train.png');}'''
        style_bt3 = '''#butt_words{background-image:url('view/img/but-tianjia.png');}'''
        style_bt4 = '''#butt_erbook{background-image:url('view/img/but-shuji.png');}'''
        style_bt5 = '''#butt_test{background-image:url('view/img/but-game.png');}'''
        style_bt6 = '''#butt_guanWang{background-image:url('view/img/but-guanwang.png');}'''

        self.butt_fanyi.setStyleSheet(style_bt1)
        self.butt_wordTrain.setStyleSheet(style_bt2)
        self.butt_words.setStyleSheet(style_bt3)
        self.butt_erbook.setStyleSheet(style_bt4)
        self.butt_test.setStyleSheet(style_bt5)
        self.butt_guanWang.setStyleSheet(style_bt6)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "易背单词"))
        self.out_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:11pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt; font-weight:400;\"><br /></p></body></html>"))
        self.butt_range.setText(_translate("MainWindow", "&r翻译"))#设置alt+r的快捷键
        self.input_text.setPlaceholderText(_translate("MainWindow", "\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址\n请输入你要翻译的文字或网址"))
        self.butt_return.setText(_translate("MainWindow", "&q清除"))#设置alt+q的快捷键
        self.butt_fanyi.setText(_translate("MainWindow", "   有道翻译"))
        self.butt_wordTrain.setText(_translate("MainWindow", "   单词训练"))
        self.butt_words.setText(_translate("MainWindow", "   添加词汇"))
        self.butt_erbook.setText(_translate("MainWindow", "   查看词汇"))
        self.butt_test.setText(_translate("MainWindow", "   娱乐休闲"))
        self.butt_guanWang.setText(_translate("MainWindow", "   软件说明"))
        self.user.setTitle(_translate("MainWindow", "用户信息"))
        self.help.setTitle(_translate("MainWindow", "帮助"))
        self.help_about.setTitle(_translate("MainWindow", "关于"))
        self.user_set.setText(_translate("MainWindow", "修改密码"))
        self.user_add.setText(_translate("MainWindow", "添加用户"))
        self.user_out.setText(_translate("MainWindow", "退出登录"))
        self.help_fund.setText(_translate("MainWindow", "搜索"))
        self.help_about_help.setText(_translate("MainWindow", "help"))
        self.help_about_check.setText(_translate("MainWindow", "检查更新"))
        self.label_bz.setText(_translate("MainWindow", "单词备注:"))
        self.lien_bz.setText(_translate("MainWindow", "None"))
